export const ActionTypes ={
    SET_PRODUCTS : 'SET_PRODUCTS',
    SET_DISCRIPTION:'SET_DISCRIPTION',
    SET_USER: 'SET_USER',
    SET_CART: 'SET_CART',
    SET_TOTAL:'SET_TOTAL',
    SET_LENGTH: 'SET_LENGTH'
}